# Generated by Django 3.2.1 on 2022-05-11 12:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва')),
                ('state_number', models.CharField(help_text='Код регіону__регістраційний номер__серія', max_length=10, null=True, verbose_name='Державний номер')),
                ('category', models.IntegerField(choices=[(1, 'B'), (2, 'C1'), (3, 'C')], verbose_name='Водійська категорія')),
                ('mileage', models.FloatField(blank=True, default=0, verbose_name='Пробіг')),
                ('load_capacity', models.FloatField(help_text='Вказувати в кілограмах', verbose_name='Вантажопідйомність')),
                ('width', models.FloatField(help_text='Вказувати в метрах', verbose_name='Ширина кузова')),
                ('length', models.FloatField(help_text='Вказувати в метрах', verbose_name='Довжина кузова')),
                ('height', models.FloatField(help_text='Вказувати в метрах', verbose_name='Висота кузова')),
                ('type_fuel', models.PositiveSmallIntegerField(choices=[(1, 'БЕНЗИН'), (2, 'ДИЗЕЛЬ'), (3, 'ГАЗ')], verbose_name='Тип палива')),
                ('tank_size', models.FloatField(help_text='В літрах', null=True, verbose_name='Розмір баку')),
                ('fuel_consumption', models.FloatField(null=True, verbose_name='Споживання палива на 100 км')),
                ('is_repair', models.BooleanField(default=False, verbose_name='Авто ремонтується')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Коли ремонт буде завершено?')),
                ('what_repair', models.CharField(blank=True, max_length=200, null=True, verbose_name='Що ремонтується?')),
                ('cost', models.PositiveIntegerField(blank=True, help_text='В грн.', null=True, verbose_name='Вартість ремонту')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'B'), (2, 'C1'), (3, 'C')], max_length=5, null=True, verbose_name='Категорії водія')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Водій',
                'verbose_name_plural': 'Водії',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджери',
            },
        ),
        migrations.CreateModel(
            name='RegistrationRefueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_refueling', models.DateField(default=datetime.datetime(2022, 5, 11, 12, 46, 28, 698701, tzinfo=utc), verbose_name='Дата заправки')),
                ('type_fuel', models.CharField(choices=[(1, 'БЕНЗИН'), (2, 'ДИЗЕЛЬ'), (3, 'ГАЗ')], max_length=20, null=True, verbose_name='Тип палива')),
                ('amount_fuel', models.FloatField(help_text='В літрах', null=True, verbose_name='Кількість палива')),
                ('price', models.FloatField(help_text='В грн.', null=True, verbose_name='Вартість палива')),
                ('total_price', models.FloatField(help_text='В грн.', null=True, verbose_name='Загальна вартість')),
                ('fuel_check', models.ImageField(null=True, unique=True, upload_to='checks/', verbose_name='Чек, для бухгалтерії')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.car', verbose_name='Автомобіль')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.driver', verbose_name='Водій')),
            ],
            options={
                'verbose_name': 'Реєстрація заправки',
                'verbose_name_plural': 'Реєстрація заправок',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Нова заявка'), (2, 'В обробці'), (3, 'Очікує погрузку'), (4, 'Завершено')], default=1, verbose_name='Статус заявки')),
                ('product', models.CharField(max_length=255, null=True, verbose_name='Що бажаєте замовити на доставку?')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я отримувача")),
                ('phone', models.CharField(default='+380', max_length=20, verbose_name='Телефон отримувача')),
                ('address', models.CharField(blank=True, help_text='Область, населений пункт, вулиця, номер будинку та квартири(за потребою)', max_length=255, null=True, verbose_name='Адреса отримувача')),
                ('date_trip', models.DateField(default=datetime.datetime(2022, 5, 11, 12, 46, 28, 698206, tzinfo=utc), verbose_name='Дата доставки')),
                ('total_distance', models.FloatField(default=0, help_text='Вказується в кілометрах', verbose_name='Загальна відстань рейсу')),
                ('amount_trip', models.PositiveSmallIntegerField(default=1, verbose_name='Кількість поїздок')),
                ('car', models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_repair', False)), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.car', unique_for_date='date_trip', verbose_name='Автомобіль')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.driver', unique_for_date='date_trip', verbose_name='Водій')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.manager', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.driver', verbose_name='Відповідальний водій'),
        ),
    ]
