# Generated by Django 3.2.1 on 2022-05-11 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 12, 46, 36, 427184, tzinfo=utc), verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='date_refueling',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 12, 46, 36, 427677, tzinfo=utc), verbose_name='Дата заправки'),
        ),
    ]
