# Generated by Django 3.2.1 on 2022-05-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseInfo',
        ),
    ]
