# Generated by Django 3.2.1 on 2022-05-08 07:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0002_delete_baseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Нова заявка'), (2, 'В обробці'), (3, 'Готується до відправки'), (4, 'Завершено')], null=True, verbose_name='Статус заявки')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я отримувача")),
                ('phone', models.CharField(default='+380 ', max_length=20, verbose_name='Телефон отримувача')),
                ('address', models.CharField(blank=True, help_text='Область, населений пункт, вулиця, номер будинку та квартири(за потребою)', max_length=255, null=True, verbose_name='Адреса отримувача')),
                ('date_trip', models.DateField(default=datetime.date.today, verbose_name='Дата доставки')),
                ('order_weight', models.PositiveIntegerField(default=0, help_text='Введіть приблизну загальну вагу в кілограмах', verbose_name='Загальна вага')),
                ('total_distance', models.FloatField(help_text='Вказується в кілометрах', null=True, verbose_name='Загальна відстань рейсу')),
                ('amount_trip', models.PositiveSmallIntegerField(default=1, verbose_name='Кількість поїздок')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='mileage',
            field=models.FloatField(blank=True, default=0, verbose_name='Пробіг'),
        ),
        migrations.AddField(
            model_name='driver',
            name='mileage',
            field=models.FloatField(blank=True, default=0, verbose_name='Пробіг'),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.driver', verbose_name='Водій'),
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.cars', verbose_name='Автомобіль'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Замовник'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.driver', verbose_name='Водій'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.manager', verbose_name='Замовник'),
        ),
    ]
