# Generated by Django 3.2.1 on 2022-05-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20220508_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='+380 ', max_length=20, verbose_name='Номер телефону'),
        ),
    ]
