# Generated by Django 3.2.1 on 2022-05-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customer', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField()),
            ],
        ),
    ]
