# Generated by Django 3.2.1 on 2022-05-12 09:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20220512_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_trip',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 9, 7, 0, 850186, tzinfo=utc), verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='date_refueling',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 9, 7, 0, 850394, tzinfo=utc), verbose_name='Дата заправки'),
        ),
    ]
