# Generated by Django 3.2.1 on 2022-05-08 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0005_isroles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isroles',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='isroles',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='isroles',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='isroles',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
