# Generated by Django 3.2.1 on 2022-05-12 09:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20220512_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.RemoveField(
            model_name='car',
            name='height',
        ),
        migrations.RemoveField(
            model_name='car',
            name='length',
        ),
        migrations.RemoveField(
            model_name='car',
            name='width',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='registrationrefueling',
            name='total_price',
        ),
        migrations.AddField(
            model_name='car',
            name='driver_class',
            field=models.IntegerField(choices=[(1, 'B'), (2, 'C1'), (3, 'C')], default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='height_trunk',
            field=models.FloatField(default=0, help_text='In meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='length_trunk',
            field=models.FloatField(default=0, help_text='In meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='width_trunk',
            field=models.FloatField(default=0, help_text='In meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_class',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'B'), (2, 'C1'), (3, 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='cost',
            field=models.PositiveIntegerField(blank=True, help_text='In UAH', null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.driver'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_consumption',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_repair',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='load_capacity',
            field=models.FloatField(help_text='In kilograms'),
        ),
        migrations.AlterField(
            model_name='car',
            name='state_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='tank_size',
            field=models.FloatField(help_text='In liters', null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_fuel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'GASOLINE'), (2, 'DIESEL'), (3, 'GAS')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='what_repair',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_repair', False)), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.car', unique_for_date='date_trip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 9, 52, 45, 172573, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.driver', unique_for_date='date_trip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.manager'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='+380', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NEW'), (2, 'IN PROCESSING'), (3, 'PREPARE TO SHIP'), (4, 'DONE')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_distance',
            field=models.FloatField(default=0, help_text='In kilometers'),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='amount_fuel',
            field=models.FloatField(help_text='In liters', null=True),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.car'),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='date_refueling',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 9, 52, 45, 172803, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.driver'),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='fuel_check',
            field=models.ImageField(null=True, unique=True, upload_to='checks/'),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='type_fuel',
            field=models.CharField(choices=[(1, 'GASOLINE'), (2, 'DIESEL'), (3, 'GAS')], max_length=20, null=True),
        ),
    ]
