# Generated by Django 3.2.1 on 2022-05-12 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20220512_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 10, 0, 56, 284493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='date_refueling',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 10, 0, 56, 284684, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='fuel_check',
            field=models.ImageField(unique=True, upload_to='checks/'),
        ),
    ]
