# Generated by Django 3.2.1 on 2022-05-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_isroles_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
    ]
