# Generated by Django 3.2.1 on 2022-05-12 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20220512_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_refueling', models.DateField(default=datetime.datetime(2022, 5, 12, 15, 9, 16, 511563, tzinfo=utc))),
                ('type_fuel', models.CharField(choices=[(1, 'GASOLINE'), (2, 'DIESEL'), (3, 'GAS')], max_length=20, null=True)),
                ('amount_fuel', models.FloatField(help_text='In liters', null=True)),
                ('price', models.FloatField(help_text='In UAH', null=True)),
                ('fuel_check', models.ImageField(unique=True, upload_to='checks/')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='delivery.car')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.driver')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 15, 9, 16, 511339, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='RegistrationRefueling',
        ),
    ]
