# Generated by Django 3.2.1 on 2022-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_order_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=255, null=True, verbose_name='Що бажаєте замовити на доставку?'),
        ),
    ]
