# Generated by Django 3.2.1 on 2022-05-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_order_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Замовник', 'verbose_name_plural': 'Замовники'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджери'},
        ),
    ]
