# Generated by Django 3.2.1 on 2022-05-08 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_auto_20220508_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата народження'),
        ),
    ]
