# Generated by Django 3.2.1 on 2022-05-08 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_customer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='fuel_consumption',
            field=models.FloatField(null=True, verbose_name='Споживання палива на 100 км'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='load_capacity',
            field=models.FloatField(help_text='Вказувати в кілограмах', null=True, verbose_name='Вантажопідйомність'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='responsible_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.driver', verbose_name='Відповідальний водій'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Нова заявка'), (2, 'В обробці'), (3, 'Готується до відправки'), (4, 'Завершено')], default=1, verbose_name='Статус заявки'),
        ),
    ]
