# Generated by Django 3.2.1 on 2022-05-12 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_auto_20220512_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueling',
            name='date_refueling',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 18, 54, 3, 235101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 18, 54, 3, 234912, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 18, 54, 3, 234709, tzinfo=utc)),
        ),
    ]
