# Generated by Django 3.2.1 on 2022-05-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_auto_20220508_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_weight',
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.cars', verbose_name='Автомобіль'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.driver', verbose_name='Водій'),
        ),
    ]
