# Generated by Django 3.2.1 on 2022-05-14 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_auto_20220512_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair',
            name='driver',
        ),
        migrations.AlterField(
            model_name='car',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.driver'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driver_class',
            field=models.PositiveIntegerField(choices=[(1, 'B'), (2, 'C1'), (3, 'C')], default=1),
        ),
        migrations.AlterField(
            model_name='fueling',
            name='date_refueling',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 14, 9, 32, 566624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 14, 9, 32, 566425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='car',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_repair', True)), on_delete=django.db.models.deletion.CASCADE, to='delivery.car'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 14, 9, 32, 566216, tzinfo=utc)),
        ),
    ]
