# Generated by Django 3.2.1 on 2022-05-14 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_auto_20220514_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueling',
            name='date_refueling',
        ),
        migrations.AddField(
            model_name='fueling',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='fueling',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 14, 51, 31, 962418, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 14, 51, 31, 962127, tzinfo=utc)),
        ),
    ]
