# Generated by Django 3.2.1 on 2022-05-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_auto_20220508_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
