# Generated by Django 3.2.1 on 2022-05-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_remove_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isroles',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='IsRoles',
        ),
    ]
