# Generated by Django 3.2.1 on 2022-05-14 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_auto_20220514_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_class',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'B'), (2, 'C1'), (3, 'C')], default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='fueling',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='In UAH', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 15, 51, 57, 962602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 15, 51, 57, 962349, tzinfo=utc)),
        ),
    ]
