# Generated by Django 3.2.1 on 2022-05-16 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_auto_20220516_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 13, 43, 55, 435002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NEW'), (2, 'PREPARE TO SHIP'), (3, 'DONE')], default=1),
        ),
        migrations.AlterField(
            model_name='repair',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 13, 43, 55, 434755, tzinfo=utc)),
        ),
    ]
