# Generated by Django 3.2.1 on 2022-05-08 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_alter_order_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.driver', unique_for_date='date_trip', verbose_name='Водій'),
        ),
    ]
