# Generated by Django 3.2.1 on 2022-05-16 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_auto_20220516_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='height_trunk',
            field=models.DecimalField(decimal_places=2, help_text='In meters', max_digits=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='length_trunk',
            field=models.DecimalField(decimal_places=2, help_text='In meters', max_digits=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='load_capacity',
            field=models.DecimalField(decimal_places=2, help_text='In kilograms', max_digits=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='tank_size',
            field=models.DecimalField(decimal_places=2, help_text='In liters', max_digits=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='width_trunk',
            field=models.DecimalField(decimal_places=2, help_text='In meters', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fueling',
            name='amount_fuel',
            field=models.DecimalField(decimal_places=2, help_text='In liters', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_repair', False)), on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.car', unique_for_date='date_trip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 18, 10, 32, 838519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.driver', unique_for_date='date_trip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.manager'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, help_text='In kilometers', max_digits=12),
        ),
        migrations.AlterField(
            model_name='repair',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='In UAH', max_digits=12),
        ),
        migrations.AlterField(
            model_name='repair',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 18, 10, 32, 838274, tzinfo=utc)),
        ),
    ]
