# Generated by Django 3.2.1 on 2022-05-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_auto_20220508_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='tank_size',
            field=models.FloatField(null=True, verbose_name='Розмір баку'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name="Ім'я та прізвище"),
        ),
    ]
