# Generated by Django 3.2.1 on 2022-05-17 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_auto_20220516_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 17, 9, 39, 49, 260959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 5, 17, 9, 39, 49, 260718, tzinfo=utc)),
        ),
    ]
