# Generated by Django 3.2.1 on 2022-05-09 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_auto_20220509_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrefueling',
            name='date_refueling',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата заправки'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='tank_size',
            field=models.FloatField(help_text='В літрах', null=True, verbose_name='Розмір баку'),
        ),
    ]
