# Generated by Django 3.2.1 on 2022-05-17 11:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_auto_20220517_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_repair', False)), on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery.car', unique_for_date='date_trip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 17, 11, 12, 53, 511386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery.driver', unique_for_date='date_trip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery.manager'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 5, 17, 11, 12, 53, 511136, tzinfo=utc)),
        ),
    ]
