# Generated by Django 3.2.1 on 2022-05-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_auto_20220509_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrefueling',
            name='fuel_check',
            field=models.ImageField(null=True, unique=True, upload_to='checks/', verbose_name='Чек, для бухгалтерії'),
        ),
    ]
