# Generated by Django 3.2.1 on 2022-05-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_cars_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrefueling',
            name='car',
            field=models.ForeignKey(limit_choices_to=models.Q(('repair', True)), null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.cars', verbose_name='Автомобіль'),
        ),
    ]
