# Generated by Django 3.2.1 on 2022-05-20 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0026_auto_20220520_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueling',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 20, 12, 21, 40, 839178, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 20, 12, 21, 40, 838995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 5, 20, 12, 21, 40, 838801, tzinfo=utc)),
        ),
    ]
