# Generated by Django 3.2.1 on 2022-05-18 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0026_auto_20220518_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='all_mileage',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 17, 4, 8, 81804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 17, 4, 8, 81615, tzinfo=utc)),
        ),
    ]
