# Generated by Django 3.2.1 on 2022-05-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0026_auto_20220509_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repairs',
            options={'verbose_name': 'Авто в ремонті', 'verbose_name_plural': 'Автомобілі в ремонті'},
        ),
        migrations.AlterField(
            model_name='repairs',
            name='cost',
            field=models.PositiveIntegerField(help_text='В грн.', null=True, verbose_name='Вартість ремонту'),
        ),
    ]
