# Generated by Django 3.2.1 on 2022-05-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0027_auto_20220509_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name="Ім'я та прізвище"),
        ),
    ]
