# Generated by Django 3.2.1 on 2022-05-22 12:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0027_auto_20220520_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueling',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fueling',
            name='driver',
        ),
        migrations.AlterField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.driver'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 12, 11, 13, 643429, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='car',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_repair', True)), on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='delivery.car'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 12, 11, 13, 643246, tzinfo=utc)),
        ),
    ]
