# Generated by Django 3.2.1 on 2022-05-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0028_alter_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Нова заявка', 'Нова заявка'), ('В обробці', 'В обробці'), ('Готується до відправки', 'Готується до відправки'), ('Завершено', 'Завершено')], default='Нова заявка', max_length=30, verbose_name='Статус заявки'),
        ),
    ]
