# Generated by Django 3.2.1 on 2022-05-22 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0028_auto_20220522_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueling',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car', to='delivery.car'),
        ),
        migrations.AlterField(
            model_name='fueling',
            name='type_fuel',
            field=models.CharField(choices=[(1, 'GASOLINE'), (2, 'DIESEL'), (3, 'GAS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_trip',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 12, 47, 31, 191583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 12, 47, 31, 191397, tzinfo=utc)),
        ),
    ]
