# Generated by Django 3.2.1 on 2022-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0029_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='type_fuel',
            field=models.CharField(choices=[(1, 'БЕНЗИН'), (2, 'Дизель'), (3, 'ГАЗ')], max_length=20, null=True, verbose_name='Тип палива'),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='type_fuel',
            field=models.CharField(choices=[(1, 'БЕНЗИН'), (2, 'Дизель'), (3, 'ГАЗ')], max_length=20, null=True, verbose_name='Тип палива'),
        ),
    ]
