# Generated by Django 3.2.1 on 2022-05-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0030_auto_20220509_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='type_fuel',
            field=models.CharField(choices=[('БЕНЗИН', 'БЕНЗИН'), ('ДИЗЕЛЬ', 'ДИЗЕЛЬ'), ('ГАЗ', 'ГАЗ')], max_length=20, null=True, verbose_name='Тип палива'),
        ),
        migrations.AlterField(
            model_name='registrationrefueling',
            name='type_fuel',
            field=models.CharField(choices=[('БЕНЗИН', 'БЕНЗИН'), ('ДИЗЕЛЬ', 'ДИЗЕЛЬ'), ('ГАЗ', 'ГАЗ')], max_length=20, null=True, verbose_name='Тип палива'),
        ),
    ]
