# Generated by Django 3.2.1 on 2022-05-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0031_auto_20220509_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Коли ремонт буде завершено?'),
        ),
    ]
