# Generated by Django 3.2.1 on 2022-05-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0032_cars_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='repair',
            new_name='is_repair',
        ),
        migrations.AddField(
            model_name='cars',
            name='cost',
            field=models.PositiveIntegerField(blank=True, help_text='В грн.', null=True, verbose_name='Вартість ремонту'),
        ),
        migrations.AddField(
            model_name='cars',
            name='what_repair',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Що ремонтується?'),
        ),
        migrations.DeleteModel(
            name='Repairs',
        ),
    ]
