# Generated by Django 3.2.1 on 2022-05-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0033_auto_20220509_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='is_repair',
        ),
        migrations.AddField(
            model_name='cars',
            name='repair',
            field=models.BooleanField(default=False, verbose_name='Авто ремонтується'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='what_repair',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Що ремонтується?'),
        ),
    ]
