# Generated by Django 3.2.1 on 2022-05-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0035_rename_repair_cars_is_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_repair', False)), null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.cars', unique_for_date='date_trip', verbose_name='Автомобіль'),
        ),
    ]
