# Generated by Django 3.2.1 on 2022-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0036_alter_order_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Нова заявка', 'Нова заявка'), ('В обробці', 'В обробці'), ('Очікує погрузку', 'Очікує погрузку'), ('Завершено', 'Завершено')], default='Нова заявка', max_length=30, verbose_name='Статус заявки'),
        ),
    ]
