# Generated by Django 3.2.1 on 2022-05-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0037_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='height',
            field=models.FloatField(help_text='Вказувати в метрах', null=True, verbose_name='Висота товару(ів)'),
        ),
        migrations.AddField(
            model_name='order',
            name='length',
            field=models.FloatField(help_text='Вказувати в метрах', null=True, verbose_name='Довжина товару(ів)'),
        ),
        migrations.AddField(
            model_name='order',
            name='width',
            field=models.FloatField(help_text='Вказувати в метрах', null=True, verbose_name='Ширина товару(ів)'),
        ),
    ]
