# Generated by Django 3.2.1 on 2022-05-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0038_auto_20220510_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='height',
            field=models.FloatField(blank=True, help_text='Вказувати в метрах', null=True, verbose_name='Висота товару(ів)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='length',
            field=models.FloatField(blank=True, help_text='Вказувати в метрах', null=True, verbose_name='Довжина товару(ів)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='width',
            field=models.FloatField(blank=True, help_text='Вказувати в метрах', null=True, verbose_name='Ширина товару(ів)'),
        ),
    ]
