# Generated by Django 3.2.1 on 2022-05-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0039_auto_20220510_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='height',
        ),
        migrations.RemoveField(
            model_name='order',
            name='length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='width',
        ),
    ]
