# Generated by Django 3.2.1 on 2022-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0040_auto_20220510_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Пробіг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, help_text='Вказується в кілометрах', max_digits=12, null=True, verbose_name='Загальна відстань рейсу'),
        ),
    ]
