# Generated by Django 3.2.1 on 2022-05-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0041_auto_20220511_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.FloatField(blank=True, default=0, verbose_name='Пробіг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_distance',
            field=models.FloatField(help_text='Вказується в кілометрах', null=True, verbose_name='Загальна відстань рейсу'),
        ),
    ]
