# Generated by Django 3.2.1 on 2022-05-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0042_auto_20220511_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='mileage',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_distance',
            field=models.IntegerField(help_text='Вказується в кілометрах', null=True, verbose_name='Загальна відстань рейсу'),
        ),
    ]
