# Generated by Django 3.2.1 on 2022-05-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0043_auto_20220511_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.driver', unique_for_date='date_trip', verbose_name='Водій'),
        ),
    ]
