# Generated by Django 3.2.1 on 2022-05-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0044_alter_order_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='mileage',
            field=models.IntegerField(blank=True, default=0, verbose_name='Пробіг'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.IntegerField(blank=True, default=0, verbose_name='Пробіг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.driver', unique_for_date='date_trip', verbose_name='Водій'),
        ),
    ]
