# Generated by Django 3.2.1 on 2022-05-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0045_auto_20220511_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.FloatField(blank=True, default=0, verbose_name='Пробіг'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробіг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_distance',
            field=models.FloatField(default=0, help_text='Вказується в кілометрах', verbose_name='Загальна відстань рейсу'),
        ),
    ]
