# Generated by Django 3.2.1 on 2022-05-11 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0046_auto_20220511_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='mileage',
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_repair', False)), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.cars', unique_for_date='date_trip', verbose_name='Автомобіль'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.driver', unique_for_date='date_trip', verbose_name='Водій'),
        ),
    ]
