# Generated by Django 3.2.1 on 2022-05-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0047_auto_20220511_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Нова заявка'), (2, 'В обробці'), (3, 'Очікує погрузку'), (4, 'Завершено')], default=1, max_length=30, verbose_name='Статус заявки'),
        ),
    ]
